language: php
php:
- '7.1'
before_script:
- composer install
notifications:
  on_success: change
  on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: nuCaJKVk5ls+eq6E/ZFm952lHiBLFl9PZjX5UZjWT88Xkr3+QVEFmVBHfZF7R12ZGnwM6lY3RYqivoln4oFI5R5eWrmTvNxP7Qoyk3mxrLMrZ7+pixUBXZKN1BCSNYRqWqHguaxpR8+wW1ZXILFAT0MhIqw8EjcepsWQy2N9zpQuDjvIxW/bFcstnXuwe6rYAxpt15PkyxSKlfk5XSnO3OPO/WkHTYY3NX20YPK0VRz7KX5nszMGDNDyHiRGPGx2FU5vFq6ISZREeXxDBkwNr1Slzg6vN8UuGdI1Q1Y0uvQmKCaoCvM5zvKM2T/a7hzjCCX8JjZh5ETSAhR2pLMPEgnm0eomR4OBiw3CwX6S3DNPEc8yHpEGMuzWuL0l3pIKgTIZcLz4obqzIxkajBMPY10SIPcUMRJWHOAvLPgMZg8gLvv1eCx8hNezmdkPR4HDdbhLtDK8KMxsf+V+pjzi3v84PONsf4DNmLh9+oUer/nMLIQe2qNv2u3y4ZpAocsgMxpsUzdFhk6UN6aZ9tZo//LlyzSLdmfgkj7ZrUXV9kvNh1SNU32HAK81bOuhg4SGxGJz+TB1mZEdPmiG2almg+VjXZAPwo29mw3RAyAySRjrspGQZGnKYTiUeB84S+HCar9mxDucxUmDVjCYBiNvzFRLDO6QnNMGQF+Vrlj28HA=
  app: glacial-retreat-28903
  on:
    repo: vmonjaret/symfony-boilerplate
