language: php
php:
- '7.1'
before_script:
- composer install
notifications:
  on_success: change
  on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: pXHC+7JDfUdA4WCVECkRPGGGZplMH5XfUBQpuckdzE6qwfSmxBbOhZN6XtyenlGUd3bwrns7MnkwGj2jU3oMfknLDgDnLcOpAcBH4RRMQVDkS3ae7NhVfK8HDxAMN0HGGi/UThz/TtuH+gmRgyn6Opi2niP/kV8FjPxeCYU6t7aEsNbBlVkGgq/LG4BtoDxTpZ1wfqWUNThwXUsmBa402fHXa62/AnBHSesAindzK0a9u+XPLGwhQf8P+2AQ47sdtuq/CJlITzwqo5Bniln+2q92N7CAK7fe/d8DQsbxrHVTSuSOLUkFyUa8vIYTHLScfIDXyUCeZbXD7/A3K3v03hi7XBzTT64kHvagNNFiteUp6hdTirqCM/nV0o+d59orr2Kn5NCYxa5kRWcul7f3Nz3C8SU8AoWAA7IVzn45xPnAAp9ZqVvD0H/horgXFgKZSSJNrqKlKJiEHkM3DDDUt8d+/W/1CT14woBNhruHxwHeXpxRmMkYS7kmHGiBkzWoglSttslmOZlUPYNOWgcQX+6hUQJk2dHwdrgCSF39/0004ccEq6c1LBq1qGQJbdjlhQKr337EKnlDCMJkNGz79rPj5UnqjEDr1fK0uxtubOaIo/elb7atSzhkOBW7SoOFsh+DPz14nGoulldQYy0NpOzpwDFTY1yPfrr/euH5540=
  app: glacial-retreat-28903
  on:
    repo: vmonjaret/symfony-boilerplate
