version: '2'

services:
    db:
        image: mariadb
        volumes:
            - "./.data/db:/var/lib/mysql"
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
    php:
        build:
            context: ./docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
    nginx:
        build:
            context: ./docker/nginx
            args:
                PROJECT_NAME: ${PROJECT_NAME}
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./.logs/nginx/:/var/log/nginx
    maildev:
        image: djfarrelly/maildev
        ports:
            - 8000:80